/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfitRouteImport } from './routes/profit'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CollectRouteImport } from './routes/collect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceiptLoanIdRouteImport } from './routes/receipt.$loanId'
import { Route as CustomersNewRouteImport } from './routes/customers.new'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as CollectorsUsernameRouteImport } from './routes/collectors.$username'
import { Route as ReceiptSavingSavingIdRouteImport } from './routes/receipt.saving.$savingId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitRoute = ProfitRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectRoute = CollectRouteImport.update({
  id: '/collect',
  path: '/collect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptLoanIdRoute = ReceiptLoanIdRouteImport.update({
  id: '/receipt/$loanId',
  path: '/receipt/$loanId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CustomersRoute,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRoute,
} as any)
const CollectorsUsernameRoute = CollectorsUsernameRouteImport.update({
  id: '/collectors/$username',
  path: '/collectors/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptSavingSavingIdRoute = ReceiptSavingSavingIdRouteImport.update({
  id: '/receipt/saving/$savingId',
  path: '/receipt/saving/$savingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collect': typeof CollectRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/profit': typeof ProfitRoute
  '/reports': typeof ReportsRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRoute
  '/collectors/$username': typeof CollectorsUsernameRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/receipt/$loanId': typeof ReceiptLoanIdRoute
  '/receipt/saving/$savingId': typeof ReceiptSavingSavingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collect': typeof CollectRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/profit': typeof ProfitRoute
  '/reports': typeof ReportsRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRoute
  '/collectors/$username': typeof CollectorsUsernameRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/receipt/$loanId': typeof ReceiptLoanIdRoute
  '/receipt/saving/$savingId': typeof ReceiptSavingSavingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collect': typeof CollectRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/profit': typeof ProfitRoute
  '/reports': typeof ReportsRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRoute
  '/collectors/$username': typeof CollectorsUsernameRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/receipt/$loanId': typeof ReceiptLoanIdRoute
  '/receipt/saving/$savingId': typeof ReceiptSavingSavingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collect'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/loans'
    | '/login'
    | '/profit'
    | '/reports'
    | '/savings'
    | '/settings'
    | '/collectors/$username'
    | '/customers/$id'
    | '/customers/new'
    | '/receipt/$loanId'
    | '/receipt/saving/$savingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collect'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/loans'
    | '/login'
    | '/profit'
    | '/reports'
    | '/savings'
    | '/settings'
    | '/collectors/$username'
    | '/customers/$id'
    | '/customers/new'
    | '/receipt/$loanId'
    | '/receipt/saving/$savingId'
  id:
    | '__root__'
    | '/'
    | '/collect'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/loans'
    | '/login'
    | '/profit'
    | '/reports'
    | '/savings'
    | '/settings'
    | '/collectors/$username'
    | '/customers/$id'
    | '/customers/new'
    | '/receipt/$loanId'
    | '/receipt/saving/$savingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectRoute: typeof CollectRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ExpensesRoute: typeof ExpensesRoute
  LoansRoute: typeof LoansRoute
  LoginRoute: typeof LoginRoute
  ProfitRoute: typeof ProfitRoute
  ReportsRoute: typeof ReportsRoute
  SavingsRoute: typeof SavingsRoute
  SettingsRoute: typeof SettingsRoute
  CollectorsUsernameRoute: typeof CollectorsUsernameRoute
  ReceiptLoanIdRoute: typeof ReceiptLoanIdRoute
  ReceiptSavingSavingIdRoute: typeof ReceiptSavingSavingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profit': {
      id: '/profit'
      path: '/profit'
      fullPath: '/profit'
      preLoaderRoute: typeof ProfitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collect': {
      id: '/collect'
      path: '/collect'
      fullPath: '/collect'
      preLoaderRoute: typeof CollectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$loanId': {
      id: '/receipt/$loanId'
      path: '/receipt/$loanId'
      fullPath: '/receipt/$loanId'
      preLoaderRoute: typeof ReceiptLoanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/collectors/$username': {
      id: '/collectors/$username'
      path: '/collectors/$username'
      fullPath: '/collectors/$username'
      preLoaderRoute: typeof CollectorsUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/saving/$savingId': {
      id: '/receipt/saving/$savingId'
      path: '/receipt/saving/$savingId'
      fullPath: '/receipt/saving/$savingId'
      preLoaderRoute: typeof ReceiptSavingSavingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CustomersRouteChildren {
  CustomersIdRoute: typeof CustomersIdRoute
  CustomersNewRoute: typeof CustomersNewRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIdRoute: CustomersIdRoute,
  CustomersNewRoute: CustomersNewRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectRoute: CollectRoute,
  CustomersRoute: CustomersRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ExpensesRoute: ExpensesRoute,
  LoansRoute: LoansRoute,
  LoginRoute: LoginRoute,
  ProfitRoute: ProfitRoute,
  ReportsRoute: ReportsRoute,
  SavingsRoute: SavingsRoute,
  SettingsRoute: SettingsRoute,
  CollectorsUsernameRoute: CollectorsUsernameRoute,
  ReceiptLoanIdRoute: ReceiptLoanIdRoute,
  ReceiptSavingSavingIdRoute: ReceiptSavingSavingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
